pipeline {
    agent any
    
    environment {
        PYTHONPATH = "${WORKSPACE}/messaging_app"
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github_cred',
                    url: 'https://github.com/legennd48/alx-backend-python.git',
                    branch: 'master'
            }
        }

        stage('Install dependencies') {
            steps {
                dir('messaging_app') {
                    sh 'python3 -m venv .venv'
                    sh '. .venv/bin/activate && pip install --upgrade pip'
                    sh '. .venv/bin/activate && pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh '. .venv/bin/activate && python -m pytest --junitxml=report.xml --verbose'
                }
            }
        }

        stage('Save Results') {
            steps {
                dir('messaging_app') {
                    junit 'report.xml'
                }
            }
            post {
                always {
                    publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'messaging_app',
                        reportFiles: 'report.xml',
                        reportName: 'Test Report'
                    ])
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline succeeded!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}