pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github_cred',
                url: 'https://github.com/legennd48/alx-backend-python.git',
                git branch: 'master'
            }
        }

    stage('Install dependencies') {
            steps {
                sh 'python3 -m venv .venv'
                sh '. .venv/bin/activate && pip install --upgrade pip'
                sh '. .venv/bin/activate && pip install -r messaging_app/requirements.txt'
            }
        }

    stage('Run Tests') {
            steps {
                sh '. .venv/bin/activate && pytest --junitxml=report.xml'
            }
        }

    stage('Save Results') {
            steps {
                junit 'report.xml'
            }
        }
}