# Kubernetes Service for Blue-Green Deployment Strategy
# This service can switch traffic between blue and green deployments
# by changing the selector labels

apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
  labels:
    app: django-messaging-app
    deployment-strategy: blue-green
  annotations:
    deployment.kubernetes.io/revision: "1"
    deployment.strategy: "blue-green"
    current.version: "blue"  # Track current active version
spec:
  selector:
    app: django-messaging-app
    version: blue  # Initially pointing to blue deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
# Separate service for testing green deployment before switching
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service-green-test
  labels:
    app: django-messaging-app
    deployment-strategy: blue-green-test
  annotations:
    deployment.strategy: "blue-green-test"
    purpose: "testing-green-deployment"
spec:
  selector:
    app: django-messaging-app
    version: green  # Points specifically to green deployment for testing
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
# Service for monitoring and health checks
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service-blue
  labels:
    app: django-messaging-app
    deployment-strategy: blue-green-monitoring
  annotations:
    deployment.strategy: "blue-green-monitoring"
    purpose: "monitoring-blue-deployment"
spec:
  selector:
    app: django-messaging-app
    version: blue  # Points specifically to blue deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
